language: python
python:
  - "3.7"
cache: pip
services:
  - postgresql
install:
  - pip install -q pipenv
  - pipenv install --system --dev
script:
  - DJANGO_SETTINGS_MODULE=antioch.settings.travis python manage.py test