{
    "DEBUG": true,
    "TEMPLATE_DEBUG": true,
    
    "DEBUG_SQL": false,
    "DEBUG_SQL_WRITES": false,
    "DEBUG_SQL_SYNTAX": false,
    
    "PROFILE_TRANSACTIONS": false,
    "PROFILE_QUEUE": false,
    "PROFILE_DB": false,
    
    "WEB_PORT": 8888,
    "APPSERVER_PORT": 8887,
    "APPSERVER_INTERFACE": "127.0.0.1",
    
    "APPSERVER_URL": "http://localhost:8887/",
    
    "PSQL_PATH": "psql",
    "JOB_TIMEOUT": 3,
    "SUPPRESS_DEPRECATION_WARNINGS": true,
    "XSENDFILE": false,
    
    # define the lookup channels in use on the site
    "AJAX_LOOKUP_CHANNELS": {
        'object': ['antioch.client.lookups', 'ObjectLookup']
    },
    
    # "SESSION_COOKIE_NAME" : "sessionid",
    
    "LOGIN_URL" : "/login/",
    "LOGIN_REDIRECT_URL" : "/",
    
    "ADMIN_FOR": ['antioch.settings'],
    
    "ADMINS":[
        ["Admin", "admin@example.com"]
    ],
    "MANAGERS":[
        ["Manager", "manager@example.com"]
    ],
    
    "DATABASES" : {
        "default" : {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "antioch",
            "USER": "antioch",
            "PASSWORD": "moavmic7",
            "HOST": "localhost",
            "PORT": ""
        }
    },

    "DB_URL_DEFAULT":"psycopg2://antioch:moavmic7@localhost/antioch",
    "DB_URL_TEST":"psycopg2://antioch:moavmic7@localhost/antioch_test",
    
    # Local time zone for this installation. Choices can be found here:
    # http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
    # although not all choices may be available on all operating systems.
    # On Unix systems, a value of None will cause Django to use the same
    # timezone as the operating system.
    # If running in a Windows environment this must be set to the same as your
    # system time zone.
    "TIME_ZONE" : "America/New_York",

    # Language code for this installation. All choices can be found here:
    # http://www.i18nguy.com/unicode/language-identifiers.html
    "LANGUAGE_CODE" : "en-us",
    "SITE_ID" : 1,

    # If you set this to False, Django will make some optimizations so as not
    # to load the internationalization machinery.
    "USE_I18N" : true,

    # If you set this to False, Django will not format dates, numbers and
    # calendars according to the current locale
    "USE_L10N" : true,

    # Absolute filesystem path to the directory that will hold user-uploaded files.
    # Example: "/home/media/media.lawrence.com/media/"
    "MEDIA_ROOT" : "",

    # URL that handles the media served from MEDIA_ROOT. Make sure to use a
    # trailing slash.
    # Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
    "MEDIA_URL" : "",

    # Absolute path to the directory static files should be collected to.
    # Don't put anything in this directory yourself; store your static files
    # in apps' "static/" subdirectories and in STATICFILES_DIRS.
    # Example: "/home/media/media.lawrence.com/static/"
    "STATIC_ROOT" : "",

    # URL prefix for static files.
    # Example: "http://media.lawrence.com/static/"
    "STATIC_URL" : "/assets/",

    # URL prefix for admin static files -- CSS, JavaScript and images.
    # Make sure to use a trailing slash.
    # Examples: "http://foo.com/static/admin/", "/static/admin/".
    "ADMIN_MEDIA_PREFIX" : "/assets/admin/",

    "STATICFILES_DIRS" : [
        # Put strings here, like "/home/html/static" or "C:/www/django/static".
        # Always use forward slashes, even on Windows.
        # Don't forget to use absolute paths, not relative paths.
    ],

    # List of finder classes that know how to find static files in
    # various locations.
    "STATICFILES_FINDERS" : [
        "django.contrib.staticfiles.finders.FileSystemFinder",
        "django.contrib.staticfiles.finders.AppDirectoriesFinder"
        #"django.contrib.staticfiles.finders.DefaultStorageFinder"
    ],

    # Make this unique, and don't share it with anybody.
    "SECRET_KEY" : "@fyj%whq0l$j5-r(bgxb0ib)4!1=l_lbye++2b9qsdrxq(c)eb",

    # List of callables that know how to import templates from various sources.
    "TEMPLATE_LOADERS" : [
        "django.template.loaders.filesystem.Loader",
        "django.template.loaders.app_directories.Loader",
        "django.template.loaders.eggs.Loader"
        
    ],

    "TEMPLATE_CONTEXT_PROCESSORS" : [
        "django.contrib.auth.context_processors.auth",
        "django.core.context_processors.debug",
        "django.core.context_processors.i18n",
        "django.core.context_processors.media",
        "django.core.context_processors.static",
        "django.core.context_processors.request",
        "django.contrib.messages.context_processors.messages",
    ],

    "MIDDLEWARE_CLASSES" : [
        "django.middleware.common.CommonMiddleware",
        "django.middleware.doc.XViewMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware"
    ],
    "ROOT_URLCONF" : "antioch.urls",
    
    "INSTALLED_APPS" : [
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sites',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.admin',
        'django.contrib.admindocs',
        'ajax_select',
        'antioch.core',
        'antioch.client',
        'antioch.assets',
        'antioch.plugins.ask',
        'antioch.plugins.editors'
    ],

    "MESSAGE_STORAGE": "django.contrib.messages.storage.session.SessionStorage",

    "AUTHENTICATION_BACKENDS" : [
        'antioch.client.DjangoBackend',
        'django.contrib.auth.backends.ModelBackend'
    ],

    # A sample logging configuration. The only tangible logging
    # performed by this configuration is to send an email to
    # the site admins on every HTTP 500 error.
    # See http://docs.djangoproject.com/en/dev/topics/logging for
    # more details on how to customize your logging configuration.
    "ACCESS_LOG": "/dev/null",
    "ERROR_LOG": "",

    "LOGGING" : {
        "version": 1,
        "disable_existing_loggers": true,
        "formatters": {
            "default": {
                "()": "antioch.util.logging.DjangoColorFormatter",
                "logformat": "[%(levelname)s] [%(name)s] %(msg)s",
                "datefmt": "%d/%b/%Y %H:%M:%S"
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "default",
                "level": "DEBUG",
            },
            "mail_admins": {
                "level": "ERROR",
                "class": "django.utils.log.AdminEmailHandler"
            }
        },
        'loggers': {
            'antioch': {
                'handlers':['console'],
                'propagate': false,
                'level':'DEBUG',
            },
            'antioch.appserver': {
                'handlers':['console'],
                'propagate': false,
                'level':'INFO',
            },
            'antioch.child': {
                'handlers':['console'],
                'propagate': false,
                'level':'INFO',
            }
            # 'django': {
            #     'handlers':['console'],
            #     'propagate': true,
            #     'level':'INFO',
            # },
            # 'django.request': {
            #     'handlers': ['console'],
            #     'level': 'INFO',
            #     'propagate': false,
            # },
        }
    },
}
