{
    "APPSERVER_INTERFACE": "0.0.0.0",
    "USE_HEROKU_DB": true,
    "QUEUE_URL": "ironmq://heroku/",
    "IRONMQ_TOKEN": "CSgWlXdfc2gb_KI3otW-iO4oo5Q",
    "IRONMQ_PROJECT_ID": "4f3581f95023e81adb000bb3"
}