{
    "APPSERVER_INTERFACE": "0.0.0.0",
    "HEROKU_ENV" : {
        "QUEUE_URL": "RABBITMQ_URL",
        "DATABASE_URL": "DATABASE_URL",
        "DATABASE_URL": "DB_URL_DEFAULT"
        # "IRON_MQ_TOKEN": "IRON_MQ_TOKEN",
        # "IRONMQ_PROJECT_ID": "IRONMQ_PROJECT_ID"
    }
}